name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_riverpod:
  riverpod_annotation:
  go_router:
  flutter_sequence_animation:
  rubber:
  sprung:
  animated_text_kit:
  cloud_firestore:
  firebase_core:
  firebase_auth:
  google_sign_in:
  http:
  auth_buttons:
  modal_progress_hud_nsn:
  firebase_storage:
  image_picker:
  path:
  equatable:
  firebase_messaging:
  flutter_local_notifications:
  flutter_launcher_icons:
  youtube_api:
  youtube_player_flutter:
  timeago:
  time:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_icons:
  image_path: "images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true
